CREATE DATABASE IF NOT EXISTS db_games;
DROP TABLE IF EXISTS db_games.game;
DROP TABLE IF EXISTS db_games.genre;
CREATE TABLE IF NOT EXISTS db_games.genre (id INT(6) PRIMARY KEY NOT NULL AUTO_INCREMENT, descript VARCHAR(255) NOT NULL);
CREATE TABLE IF NOT EXISTS db_games.game (id INT(6) PRIMARY KEY NOT NULL AUTO_INCREMENT, idGenre INT(6), descript VARCHAR(255) NOT NULL, dev VARCHAR(255) NOT NULL, style VARCHAR(255) NOT NULL, price float NOT NULL, FOREIGN KEY (idGenre) REFERENCES db_games.genre(id));